# Berksfile
#
# maintainer:: Aig Cloud Team
# maintainer_email:: aigcloudautomations@aig.com
#
# Copyright:: 2017, Aig Cloud Team, All Rights Reserved.
#
# The first source should always be the AIG Supermarket server
#

#source 'https://plgsaschefsm01.r1-core.r1.aig.net/'
source 'https://supermarket.chef.io'

metadata
